BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Users" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Email"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"Role"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	FOREIGN KEY("Role") REFERENCES "RoleMap"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "OrderItem" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Order"	INTEGER NOT NULL,
	"Item"	INTEGER NOT NULL,
	"Quantity"	INTEGER NOT NULL,
	"Price"	NUMERIC NOT NULL,
	FOREIGN KEY("Item") REFERENCES "Item"("ID"),
	FOREIGN KEY("Order") REFERENCES "Order"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Order" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"User"	INTEGER NOT NULL,
	"OrderDate"	NUMERIC NOT NULL,
	"DeliveryDate"	NUMERIC NOT NULL,
	"CancelDate"	NUMERIC NOT NULL,
	"FinishDate"	NUMERIC,
	"Status"	INTEGER NOT NULL,
	FOREIGN KEY("Status") REFERENCES "StatusMap"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("User") REFERENCES "Users"("ID")
);
CREATE TABLE IF NOT EXISTS "StatusMap" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Description"	TEXT NOT NULL,
	"Code"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Item" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Restaurant"	INTEGER NOT NULL,
	"Price"	NUMERIC NOT NULL,
	"Quantity"	INTEGER NOT NULL DEFAULT 0,
	"Name"	TEXT NOT NULL,
	"Description"	TEXT NOT NULL,
	"CancelGracePeriod"	INTEGER NOT NULL DEFAULT 10,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("Restaurant") REFERENCES "Restaurant"("ID")
);
CREATE TABLE IF NOT EXISTS "UserReference" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"University"	INTEGER,
	"Restaurant"	INTEGER,
	"User"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("University") REFERENCES "University"("ID"),
	FOREIGN KEY("Restaurant") REFERENCES "Restaurant"("ID"),
	FOREIGN KEY("User") REFERENCES "Users"("ID")
);
CREATE TABLE IF NOT EXISTS "Restaurant" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"University"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("University") REFERENCES "University"("ID")
);
CREATE TABLE IF NOT EXISTS "University" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "RoleMap" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Description"	TEXT NOT NULL,
	"Code"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
INSERT INTO "StatusMap" ("ID","Description","Code") VALUES (1,'Pending',0),
 (2,'Accepted',1),
 (3,'Rejected',2),
 (4,'Ready',3),
 (5,'Finished',4),
 (6,'Canceled',5);
INSERT INTO "RoleMap" ("ID","Description","Code") VALUES (1,'Student',0),
 (2,'Restaurant',1);
COMMIT;
