BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Users" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Email"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"Role"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	FOREIGN KEY("Role") REFERENCES "RoleMap"("ID")
);
CREATE TABLE IF NOT EXISTS "OrderItem" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Order"	INTEGER NOT NULL,
	"Item"	INTEGER NOT NULL,
	"Quantity"	INTEGER NOT NULL,
	"Price"	NUMERIC NOT NULL,
	FOREIGN KEY("Order") REFERENCES "Order"("ID"),
	FOREIGN KEY("Item") REFERENCES "Item"("ID")
);
CREATE TABLE IF NOT EXISTS "Order" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"User"	INTEGER NOT NULL,
	"OrderDate"	NUMERIC NOT NULL,
	"DeliveryDate"	NUMERIC NOT NULL,
	"CancelDate"	NUMERIC NOT NULL,
	"FinishDate"	NUMERIC,
	"Status"	INTEGER NOT NULL,
	FOREIGN KEY("Status") REFERENCES "StatusMap"("ID"),
	FOREIGN KEY("User") REFERENCES "Users"("ID")
);
CREATE TABLE IF NOT EXISTS "StatusMap" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Description"	TEXT NOT NULL,
	"Code"	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "Item" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Restaurant"	INTEGER NOT NULL,
	"Price"	NUMERIC NOT NULL,
	"Quantity"	INTEGER NOT NULL DEFAULT 0,
	"Description"	TEXT NOT NULL,
	"CancelGracePeriod"	INTEGER NOT NULL DEFAULT 10,
	FOREIGN KEY("Restaurant") REFERENCES "Restaurant"("ID")
);
CREATE TABLE IF NOT EXISTS "UserReference" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"University"	INTEGER,
	"Restaurant"	INTEGER,
	"User"	INTEGER NOT NULL,
	FOREIGN KEY("University") REFERENCES "University"("ID"),
	FOREIGN KEY("User") REFERENCES "Users"("ID"),
	FOREIGN KEY("Restaurant") REFERENCES "Restaurant"("ID")
);
CREATE TABLE IF NOT EXISTS "Restaurant" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"University"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	FOREIGN KEY("University") REFERENCES "University"("ID")
);
CREATE TABLE IF NOT EXISTS "University" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "RoleMap" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Description"	TEXT NOT NULL,
	"Code"	INTEGER NOT NULL UNIQUE
);
INSERT INTO "StatusMap" ("ID","Description","Code") VALUES (1,'Pending',0),
 (2,'Accepted',1),
 (3,'Rejected',2),
 (4,'Ready',3),
 (5,'Finished',4),
 (6,'Canceled',5);
INSERT INTO "RoleMap" ("ID","Description","Code") VALUES (1,'Student',0),
 (2,'Restaurant',1);
COMMIT;
